### PR TITLE
Add a TravisCI YAML

### PR DESCRIPTION
**Pull request by imduffy15**
Example run at https://travis-ci.org/imduffy15/packer-post-processor-vagrant-s3

Signed-off-by: Ian Duffy ian@ianduffy.ie

### CODE REVIEW

**Comment by Jalle19** [comment]
What's the idea here? Do we want builds automatically generated and uploaded to the build host?

**Comment by Jalle19** [comment]
@imduffy15 ping

**Comment by imduffy15** [comment]
Sorry! missed the email notification.

Initial idea is to just have travisci build up the binaries on a new pull request to make sure the dependencies are still valid and that the submitter hasn't broken anything.

Going on from that it would be very easy to have travis-ci upload the binaries to github releases when a tag is created.

**Comment by Jalle19** [comment]
In that case, wouldn't it be best to build for all platforms that gox supports?

**Comment by imduffy15** [comment]
Sure! just opened the PR as an example based off https://github.com/lmars/packer-post-processor-vagrant-s3/issues/42

**Comment by lmars** [comment]
@Jalle19 any reason not to merge this? I think it is useful as is to just check things compile, we can add automated releases in a separate PR.

**Comment by Jalle19** [comment]
@lmars please hold off some more, I've testes this method on another repository and have a complete example. I'm on the phone now but I'll comment soon from a computer.

**Comment by Jalle19** [comment]
@imduffy15 @lmars I used the excellent base for a Travis configuration that you've made here and adapted it for another project here: 

https://github.com/Jalle19/packer-builder-upcloud/blob/master/.travis.yml
https://travis-ci.org/Jalle19/packer-builder-upcloud/builds/169506830
https://github.com/Jalle19/packer-builder-upcloud/releases

I limited the builds generated to just Windows/Linux/macOS and 64-bit architectures only since I figured the vast majority of developers will fall into these categories.

@imduffy15 do you think you could update this PR with this implementation as a base?

@lmars I setup the GitHub release key using `travis setup releases`. You'll need to install the Travis CLI first in order to run that (`sudo gem install travis` IIRC).

**Comment by imduffy15** [comment]
done @Jalle19

**Comment by Jalle19** [comment]
@lmars can you do the Travis setup?

**Comment by Jalle19** [comment]
@imduffy15 try adding this to `.travis.yml`:

 ```
# deploy releases to GitHub 
deploy: 
  provider: releases 
  api_key: 
    secure: pIga6euNKxU3M3PiMepgz19l5+WtS0gMrOCsXk73p79SEyhlWtl52W882zR2zqP6dEYNXGCiRjcBnTQDm4Ly+QB/9XJaJ0ROom/iwyLF6Mxzp7iTN6V8I5ZmMg5YFnfY55tBXwTjNsxC5pCZMU4awUdhF3CNLHKgil2vf2wtP5c= 
  file: 
    - packer-post-processor-vagrant-s3-${TRAVIS_TAG}-darwin-amd64.zip 
    - packer-post-processor-vagrant-s3-${TRAVIS_TAG}-linux-amd64.zip 
    - packer-post-processor-vagrant-s3-${TRAVIS_TAG}-windows-amd64.zip 
  on: 
    repo: lmars/packer-post-processor-vagrant-s3 
```

@lmars you will need to activate the project in Travis CI, I can't do that since you're the owner.

**Comment by Jalle19** [comment]
@lmars ping, do you think you could do the Travis magic so we can move forward with this?

**Pull request merged**
