### PR TITLE
Automatically generate a new minor version if none is specified

### LINKED ISSUE #24: Automatic versioning
Atlas can automatically version artifacts so that a new artifact starts at `0.1` and after that the minor version is increased every time the box is rebuilt. Something like that would be nice to have for this post-processor as well so you don't accidentally forget to bump the version before triggering a new build.

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #24

The first two commits are unrelated but quite minor so I didn't bother making a second PR for them, I hope it's okay.

### CODE REVIEW

**Comment by Jalle19** [comment]
Managed to crash the whole thing just now, I think the code doesn't yet handle existing non-semver compliant versions like `0.1`. Will update.

**Comment by Jalle19** [comment]
For reference:

```
2016/06/03 09:38:38 ui: ^[[1;32m==> virtualbox-iso: Running post-processor: vagrant-s3^[[0m
2016/06/03 09:38:42 ui: ^[[1;32m==> virtualbox-iso (vagrant-s3): Preparing to upload box for 'virtualbox' provider to S3 bucket 'nordsoftware'^[[0m
2016/06/03 09:38:42 ui: ^[[0;32m    virtualbox-iso (vagrant-s3): Box to upload: packer_virtualbox-iso_virtualbox.box (678125584 bytes)^[[0m
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: panic: runtime error: invalid memory address or nil pointer dereference
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: [signal 0xb code=0x1 addr=0x0 pc=0x401bbc]
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: goroutine 27 [running]:
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: panic(0xa58ae0, 0xc82000a170)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: main.(*Manifest).getLatestVersion(0x0, 0x0, 0x0)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /home/negge/Projects/gopath/src/github.com/jalle19/packer-post-processor-vagrant-s3/manifest.go:38 +0x1cc
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: main.(*Manifest).getNextVersion(0x0, 0x0, 0x0)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /home/negge/Projects/gopath/src/github.com/jalle19/packer-post-processor-vagrant-s3/manifest.go:54 +0x42
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: main.(*PostProcessor).PostProcess(0xc820091180, 0x7f10f83ba4b8, 0xc82023e4e0, 0x7f10f83ba500, 0xc82023e500, 0x0, 0x0, 0xc81fff3200, 0x0, 0x0)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /home/negge/Projects/gopath/src/github.com/jalle19/packer-post-processor-vagrant-s3/post-processor.go:141 +0x8c9
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: github.com/mitchellh/packer/packer/rpc.(*PostProcessorServer).PostProcess(0xc82013a360, 0x0, 0xc820194280, 0x0, 0x0)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /home/negge/Projects/gopath/src/github.com/mitchellh/packer/packer/rpc/post_processor.go:83 +0x2ed
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: reflect.Value.call(0xa11320, 0xa598c8, 0x13, 0xb58a70, 0x4, 0xc82009ded8, 0x3, 0x3, 0x0, 0x0, ...)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /usr/lib/go-1.6/src/reflect/value.go:435 +0x120d
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: reflect.Value.Call(0xa11320, 0xa598c8, 0x13, 0xc82009ded8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /usr/lib/go-1.6/src/reflect/value.go:303 +0xb1
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: net/rpc.(*service).call(0xc8201385c0, 0xc820138580, 0xc820194020, 0xc82007ca80, 0xc82017e2a0, 0x971ac0, 0xc82019402c, 0x18a, 0x92dfc0, 0xc820194280, ...)
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /usr/lib/go-1.6/src/net/rpc/server.go:383 +0x1c2
2016/06/03 09:38:42 packer-post-processor-vagrant-s3: created by net/rpc.(*Server).ServeCodec
2016/06/03 09:38:42 packer-post-processor-vagrant-s3:   /usr/lib/go-1.6/src/net/rpc/server.go:477 +0x49d
```

**Comment by Jalle19** [comment]
So I fixed the crash but the reason it was crashing was because (apparently) `getManifest()` fails:

```
==> vmware-iso: Running post-processor: vagrant-s3
==> vmware-iso (vagrant-s3): Preparing to upload box for 'vmware_desktop' provider to S3 bucket 'nordsoftware'
    vmware-iso (vagrant-s3): Box to upload: packer_vmware-iso_vmware.box (689345209 bytes)
Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

I honestly have no idea what's going on, it worked just fine yesterday.

**Comment by Jalle19** [comment]
Turns out the "the request signature does not match" issue was completely unrelated. I did notice another problem though and that is that if you build a box for two providers then the first provider will get version 0.1.0 and the second will get 0.2.0. So don't merge this yet.

**Comment by Jalle19** [comment]
That last comment was bogus, I thought there was a problem due to a weird looking manifest but it was just the symptoms of a lot of partially failed builds, nothing more. IMO this is good to go, @lmars?

**Comment by lmars** [comment]
Thanks!

**Pull request merged**
