### PR TITLE
Update dependencies for packer v1.7

### PR DESCRIPTION
**Pull request by nathan-muir**
Just a quick PR to bring compat with packer v1.6+

I'm not familiar with golang, so not sure about what it's done to `go.sum`.

Hope this helps.

### CODE REVIEW

**Comment by nathan-muir** [comment]
@matt-richardson https://github.com/3stack-software/packer-post-processor-vagrant-s3/releases/tag/unofficial

**Comment by matt-richardson** [comment]
Legend. Thanks heaps!

**Comment by Jalle19** [comment]
@matt-richardson please report back if @nathan-muir 's binary works, then I can merge this and tag a new release. I don't personally use Packer at the moment so I'm not really qualified to vouch for any major changes, but this PR looks fairly innocent (assuming it works of course).

**Comment by matt-richardson** [comment]
Hmm. Not looking to crash hot (when running on OSX at least):

```
2021/04/20 17:55:42 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-post-processor-vagrant"}
2021/04/20 17:55:42 Waiting for RPC address for: /usr/local/bin/packer
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: [INFO] Packer version: 1.7.2 [go1.16.3 darwin amd64]
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: /Users/agentuser/.packerconfig
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: [WARN] Config file doesn't exist: /Users/agentuser/.packerconfig
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: [INFO] Setting cache directory: /var/packer/cache
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: args: []string{"packer-post-processor-vagrant"}
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: Plugin address: unix /opt/TeamCity/BuildAgent/temp/buildTmp/packer-plugin799766895
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: Waiting for connection...
2021/04/20 17:55:42 Received unix RPC address for /usr/local/bin/packer: addr is /opt/TeamCity/BuildAgent/temp/buildTmp/packer-plugin799766895
2021/04/20 17:55:42 packer-post-processor-vagrant plugin: Serving a plugin connection...
2021/04/20 17:55:42 [TRACE] Starting external plugin /Users/agentuser/.packer.d/plugins/packer-post-processor-vagrant-s3 
2021/04/20 17:55:42 Starting plugin: /Users/agentuser/.packer.d/plugins/packer-post-processor-vagrant-s3 []string{"/Users/agentuser/.packer.d/plugins/packer-post-processor-vagrant-s3"}
2021/04/20 17:55:42 Waiting for RPC address for: /Users/agentuser/.packer.d/plugins/packer-post-processor-vagrant-s3
2021/04/20 17:55:43 packer-post-processor-vagrant-s3 plugin: panic: needs at least one argument
2021/04/20 17:55:43 packer-post-processor-vagrant-s3 plugin: 
2021/04/20 17:55:43 packer-post-processor-vagrant-s3 plugin: goroutine 1 [running]:
2021/04/20 17:55:43 packer-post-processor-vagrant-s3 plugin: main.main()
2021/04/20 17:55:43 packer-post-processor-vagrant-s3 plugin: 	github.com/lmars/packer-post-processor-vagrant-s3/main.go:10 +0xfc
2021/04/20 17:55:43 /Users/agentuser/.packer.d/plugins/packer-post-processor-vagrant-s3: plugin process exited
2021/04/20 17:55:43 ui error: Error: Failed to initialize build "virtualbox-iso"

error initializing post-processor 'vagrant-s3': plugin exited before we could
connect

2021/04/20 17:55:43 Build debug mode: false
2021/04/20 17:55:43 Force build: false
2021/04/20 17:55:43 On error: 
2021/04/20 17:55:43 Waiting on builds to complete...
2021/04/20 17:55:43 ui: 
==> Wait completed after 6 microseconds
2021/04/20 17:55:43 ui: 
==> Builds finished but no artifacts were created.
```

Looks like it is expecting an argument to be passed, but isn't getting one.

(also slightly confusing that it's still referencing github.com/lmars/... but I'm guessing that's a non-issue)

**Comment by matt-richardson** [comment]
Looks like there's a bunch more changes to make for this to work with 1.7 - https://packer-git-master-hashicorp.vercel.app/guides/1.7-plugin-upgrade
I'm not a golang developer, so this'll take me a while to dig into - I should have some time next week.

**Comment by nathan-muir** [comment]
I will check again tomorrow, I thought i made a second round of changes for
packet v1.7

I've been using the binaries on Ubuntu 20.04 without issue

**Comment by nathan-muir** [comment]
@matt-richardson Can you rename as follows:

```
mv ~/.packer.d/plugins/packer-post-processor-vagrant-s3 ~/.packer/plugins/packer-plugin-lmars
```

Then change usage of `vagrant-s3` to `lmars-vagrant-s3` in your packer build files.

I've tested this locally and it's working again; not sure what happened in the packer-1.7.2 upgrade...

**Comment by nathan-muir** [comment]
Ah, I might be able to fix that...

**Comment by nathan-muir** [comment]
@Jalle19 The code now supports v1.7 packer correctly.

However, if we want to support `packer init` / `required_plugins` block, the github repository needs to be renamed to `packer-plugin-vagrant-s3` [1]

Also, we need to have binaries uploaded to github releases with a specific format. [2]

[1] https://packer-git-master-hashicorp.vercel.app/docs/templates/hcl_templates/blocks/packer#specifying-plugin-requirements
[2] https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.goreleaser.yml

**Comment by matt-richardson** [comment]
Happy to report success here - this is looking pretty good on linux, and on osx and windows it at least gets past the packer plugin load validation. Thanks @nathan-muir!

**Comment by gdbonino** [comment]
Please update the documentation with the new binary name. Thanks! It's a great job!

**Pull request merged**
