### PR TITLE
Chunking of multipart uploads

### PR DESCRIPTION
**Pull request by devec0**
Hi, as discussed in previous pull request, these changes allow uploads to be done in chunks which allows for better feedback on upload process, but also allows individual 5MB chunks to be retried if they fail. I've tested this code over a few different large boxes (500-800MB) and it's working well for me.

I've incorporated feedback from the previous pull request where needed as well.

### CODE REVIEW

**Comment by dominics** [comment]
I've tested this PR, and found it quite useful. Not fun having to retry a large build because one of the hundreds of part files failed to upload because of a transient network error.

There are some outstanding `go fmt` changes that you might want to fix before/after merging.

**Comment by lmars** [comment]
@jdhebden it seems like `multi.PutPart` already [makes multiple attempts to upload parts](https://github.com/mitchellh/goamz/blob/master/s3/multi.go#L161-L190), does that not do what you expect?

**Comment by jdhebden** [comment]
@lmars - unfortunately not. There is no delay between retries, so if you lose connection even a brief second - it'll burn through the retries and the upload will fail. Plus, on a slower connection, there is no way to show progress on an upload without directly managing the part uploads - which is nice to have instead of a blinking cursor for 2+ hours :)

@dominics - seems the Internet situation is similar in NZ then ;)

**Comment by lmars** [comment]
@jdhebden I'm happy to merge this, but it conflicts with master since #13 got merged, could you rebase onto master?

**Comment by devec0** [comment]
Rebase done, onto master. Just needed to include the new ACL parameter, and include the changes to the includes for 0.8.6.

**Comment by lmars** [comment]
Thanks!

**Pull request merged**
